name: build nodejs Application in ex contonerror
on:
 workflow_dispatch:
 push:
jobs:
  job1:
   continue-on-error: true
   strategy:
     matrix:
      node-version: [12,16,18]
      operating-system: [ubuntu-latest, windows-latest]
      exclude:
      - node-version: 12
        operating-system: ubuntu-latest
      - node-version: 12
        operating-system: windows-latest
      include: # include an extra combination
      - node-version: 18
        operating-system: ubuntu-22.04


   runs-on: ${{ matrix.operating-system }}
   steps:
    - name: Clone the repo
      uses: actions/checkout@v4
    - name: Install nodejs
      uses: actions/setup-node@v4
      with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Executes test cases
      run: npm test
    - name: Build the code
      run: npm run build
    - name: Deploy the code
      run: echo 'Deploy the code'
